services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  UniversityOfCopenhagen\KuDriftinformation\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'